OUTPUT_DIR: './experiments/sigma_plus_plus/city_to_kitti/'
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: 'https://s3.ap-northeast-2.amazonaws.com/open-mmlab/pretrain/third_party/vgg16_caffe-292e1171.pth' # Initialed by imagenet
#  WEIGHT: './published_models/city_to_kitti_model_76_mAP.pth' # Initialed by our models
  RPN_ONLY: True
  FCOS_ON: True
  DA_ON: True
  ATSS_ON: False
  MIDDLE_HEAD_CFG: 'GM_HEAD'
  MIDDLE_HEAD:
    CONDGRAPH_ON: True
    IN_NORM: 'LN'
    NUM_CONVS_IN: 2
    GM:
      # SIGMA_plus_plus:
      WITH_HyperGNN: True
      HyperEdgeNum: 3
      NUM_HYPERGNN_LAYER: 1
      ANGLE_EPS: 1e-4
      # SIGMA:
      # node sampling
      NUM_NODES_PER_LVL_SR: 100
      NUM_NODES_PER_LVL_TG: 100
      BG_RATIO: 2
      # loss weight
      NODE_DIS_WEIGHT: 0.1
      NODE_DIS_LAMBDA:  0.2
      MATCHING_LOSS_WEIGHT: 0.1
      NODE_LOSS_WEIGHT: 1.0
      # detailed settings
      MATCHING_CFG: 'o2o'
      WITH_QUADRATIC_MATCHING: True
      WITH_NODE_DIS: True
      WITH_SEMANTIC_COMPLETION: True
      WITH_CLUSTER_UPDATE: True
      WITH_COMPLETE_GRAPH: True
      WITH_DOMAIN_INTERACTION: True
      WITH_SCORE_WEIGHT: False
      WITH_CTR: False
  BACKBONE:
    CONV_BODY: "VGG-16-FPN-RETINANET"
  RETINANET:
    USE_C5: False
  FCOS:
    NUM_CONVS_REG: 4
    NUM_CONVS_CLS: 4
    NUM_CLASSES: 2
    INFERENCE_TH: 0.05    # pre_nms_thresh    (default=0.05)
    PRE_NMS_TOP_N: 1000   # pre_nms_top_n     (default=1000)
    NMS_TH: 0.6           # nms_thresh        (default=0.6)
    REG_CTR_ON: True
  ADV:
    GA_DIS_LAMBDA: 0.01
    CON_NUM_SHARED_CONV_P7: 4
    CON_NUM_SHARED_CONV_P6: 4
    CON_NUM_SHARED_CONV_P5: 4
    CON_NUM_SHARED_CONV_P4: 4
    CON_NUM_SHARED_CONV_P3: 4

    USE_DIS_GLOBAL: True
    USE_DIS_P7: True
    USE_DIS_P6: True
    USE_DIS_P5: True
    USE_DIS_P4: True
    USE_DIS_P3: True

    GRL_WEIGHT_P7: 1.0
    GRL_WEIGHT_P6: 1.0
    GRL_WEIGHT_P5: 1.0
    GRL_WEIGHT_P4: 1.0
    GRL_WEIGHT_P3: 1.0
TEST:
  DETECTIONS_PER_IMG: 100 # fpn_post_nms_top_n  (default=100)
  MODE: 'common'
DATASETS:
  TRAIN_SOURCE: ("cityscapes_train_caronly_cocostyle", )
  TRAIN_TARGET: ("kitti_train_caronly", )
  TEST: ("kitti_train_caronly", )
INPUT:
  MIN_SIZE_RANGE_TRAIN: (640, 800)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  VAL_ITER: 1000
  VAL_ITER_START: 0
  INITIAL_AP50: 60
  WEIGHT_DECAY: 0.0001
  MAX_ITER: 30000 # Achieve best results at around 20000
  # 1 for source and 1 for target
  IMS_PER_BATCH: 2
  CHECKPOINT_PERIOD: 5000
  BACKBONE:
    BASE_LR: 0.0025
    STEPS: (75000, 90000) # Didn't tune and use
    WARMUP_ITERS: 1000
    WARMUP_METHOD: "constant"
  MIDDLE_HEAD:
    BASE_LR: 0.0025
    STEPS: (75000, 90000)
    WARMUP_ITERS: 1000
    WARMUP_METHOD: "constant"
    PLABEL_TH: (0.5, 1.0)
  FCOS:
    BASE_LR: 0.0025
    STEPS: (75000, 90000)
    WARMUP_ITERS: 1000
    WARMUP_METHOD: "constant"
  DIS:
    BASE_LR: 0.0025
    STEPS: (75000, 90000)
    WARMUP_ITERS: 1000
    WARMUP_METHOD: "constant"
